
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thtwvjuuonlqldnturvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRodHd2anV1b25scWxkbnR1cnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODMwMzQsImV4cCI6MjA2MjU1OTAzNH0.k9Qyyl8GQEB3Po8HxCUWO6Bya0ghxUozK6Z-akJpsn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: localStorage,
      detectSessionInUrl: true, // Ensure this is true to detect auth params in URL
      flowType: 'pkce'
    }
  }
);

// Helper function to clear auth state
export const clearAuthState = () => {
  localStorage.removeItem('supabase.auth.token');
  localStorage.removeItem('sb-thtwvjuuonlqldnturvb-auth-token');
  localStorage.removeItem('supabase.auth.refreshToken');
  
  // Clear any other auth-related localStorage items
  Object.keys(localStorage).forEach(key => {
    if (key.startsWith('supabase.auth.') || key.includes('-auth-token')) {
      localStorage.removeItem(key);
    }
  });
};

// Debug helper for auth state (useful for troubleshooting)
export const debugAuthState = async () => {
  const session = await supabase.auth.getSession();
  const user = await supabase.auth.getUser();
  return {
    session: session?.data?.session,
    user: user?.data?.user,
    localStorage: Object.keys(localStorage).filter(key => 
      key.startsWith('supabase.auth.') || key.includes('-auth-token')
    )
  };
};
