// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thtwvjuuonlqldnturvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRodHd2anV1b25scWxkbnR1cnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5ODMwMzQsImV4cCI6MjA2MjU1OTAzNH0.k9Qyyl8GQEB3Po8HxCUWO6Bya0ghxUozK6Z-akJpsn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);